# Generated by Django 5.0.6 on 2024-06-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='gender',
        ),
    ]
