# Generated by Django 5.0.6 on 2024-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_issuemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='got_relation',
            field=models.BooleanField(default=False),
        ),
    ]
