# Generated by Django 5.0.6 on 2024-06-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_profilemodel_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationmodel',
            old_name='issued_id',
            new_name='issued_by',
        ),
    ]
