# Generated by Django 5.0.6 on 2024-06-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_relationmodel_chatmodel_replymodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuemodel',
            name='prefered_char',
        ),
        migrations.AddField(
            model_name='issuemodel',
            name='preferred_char',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle')], default='father', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='character',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle')], max_length=100),
        ),
    ]
