# Generated by Django 5.0.6 on 2024-06-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_issued_id_relationmodel_issued_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationmodel',
            old_name='sugessted_by',
            new_name='suggested_by',
        ),
    ]
